name: Kawarji Scraper

on:
  schedule:
    - cron: '0 */1 * * *' 
  workflow_dispatch: 

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python scrape_kawarji.py
